apiVersion: apps/v1
kind: Deployment
metadata:
  name: client
  namespace: emart
spec:
  replicas: 2
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
      - name: client
        image: abroor/emart-client:7d33800e24a66f1604bf49bceea45b9b917befb5
        ports:
        - containerPort: 4200
