apiVersion: apps/v1
kind: Deployment
metadata:
  name: client
  namespace: emart
spec:
  replicas: 2
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
      - name: client
        image: abroor/emart-client:5eeb9aff8a330556b386f01e967e7ff4e0c37ead
        ports:
        - containerPort: 4200
