apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeapi
  namespace: emart
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodeapi
  template:
    metadata:
      labels:
        app: nodeapi
    spec:
      containers:
      - name: nodeapi
        image: abroor/emart-nodeapi:0613374fd7187571bcdc6df75eafa422bf750ab7
        ports:
        - containerPort: 5000
