apiVersion: apps/v1
kind: Deployment
metadata:
  name: javaapi
  namespace: emart
spec:
  replicas: 2
  selector:
    matchLabels:
      app: javaapi
  template:
    metadata:
      labels:
        app: javaapi
    spec:
      containers:
      - name: javaapi
        image: abroor/emart-javaapi:acd30e1f2fe0e32986e8a92028206fa5afa3b97d
        ports:
        - containerPort: 9000
